### ISSUE TITLE
issue with setting the firstDayOfWeek to Sunday on Week view

### ISSUE THREAD

**Issue by Shui-Be** [werner-scholtz/kalender#55]
Hi!

there's an issue when the firstDayOfWeek is set to DateTime.sunday but the calendar header is showing the next week's range.

in the picture below, the time range for week 17 is showing (Sun 28 - Sat 4), where it is supposed to be (Sun 21 - Sat -27), Time zone in Toronto, ON (GMT-4)
![image](https://github.com/werner-scholtz/kalender/assets/167668764/3ff2d9f7-26d0-47f6-891a-95f74187a127)

Steps to reproduce:
1. clone the app and run web_demo project
2. create a class that extends the WeekConfiguration default the firstDayOfWeek to DateTime.sunday, (this class is basically a copy of the WeekConfiguration but adding the firstDayOfWeek option, this is needed because I couldn't find any default configuration that exposes the firstDayOfWeek property):
![image](https://github.com/werner-scholtz/kalender/assets/167668764/fa9729f1-0a63-434c-8e63-e995f4d5b009)
3. run the app and see that the date range in calendar header is showing the next weeks ranges, the correct date ranges should be  Sunday April 21st 2024 - Saturday April 27th 2024 (however, the week number 17 shown in the top left does seem to be correct)

**Comment by werner-scholtz** [comment]
Hi Thanks will take a look at this.

**Comment by werner-scholtz** [comment]
Interesting the WeekConfiguration should have the super.firstDayOfWeek in the constructor.

**Comment by werner-scholtz** [comment]
Taking a look at https://en.wikipedia.org/wiki/ISO_week_date monday seems to be the start of new weeks:
What I will do is use the Monday that is displayed to calculate the week-number if Saturday / Sunday / Monday is used for firstDayOfWeek.
However if some other date is selected like Tuesday / Wednesday/ Thursday / Friday then I will display both week-numbers ex "17-18"

**Comment by kayatmin** [comment]
@werner-scholtz sry for tagging directly, thanks for the quick update.

when i switched the First day of week dropdown in the demo app from Monday to Sunday, the week number and week range seems to be displaying the next week's number and range.

a picture is worth a thousand words.. :
![image](https://github.com/werner-scholtz/kalender/assets/7703058/5b2cfd8f-377e-4b1a-b7e2-dc1cb4349491)

![image](https://github.com/werner-scholtz/kalender/assets/7703058/06efede9-f709-405f-9a75-520a911722af)

in the pictures above: my current day is April 23rd, 2024, the week range is displaying from April 28 to May 4th instead of April 21 to April 27.

**Comment by kayatmin** [comment]
@werner-scholtz yes that's correct, everything else seems to be working well, i.e., clicking on the arrow to go previous and next weeks displays the ranges correctly, callbacks returns the correct date also.

**Comment by werner-scholtz** [comment]
Okay good to know, the issue is most likely related to how [this](https://github.com/werner-scholtz/kalender/blob/cbcda04b654043e1ab8676af3b160db4b319257e/lib/src/models/view_configurations/multi_day_configurations/week_configuration.dart#L78) is calculated.
