### ISSUE TITLE
Tiles style enhancements

### ISSUE THREAD

**Issue by NobleO11** [werner-scholtz/kalender#83]
Hello @werner-scholtz ,

I was just wondering if it is possible to make a tile have more than one color. 

for example, an event that lasts 10 days, can i make the first 2 days and last 2 days show different color with the same event without creating new event? if it is not already there would you consider doing it in the next release? 

thank you so much

**Comment by werner-scholtz** [comment]
Hi, because the kalendar does not do any styling of `event tiles` itself all I can do is make it possible to do something like that. It should be possible to pass some more data to event tiles ex. the number of days spanned and the date that an event tile is rendered on, which would allow you to implement custom logic for deciding on colours. 

Would something like this work for you ?

**Comment by NobleO11** [comment]
yes this is what i am talking about, it will work perfectly, thank you
